{
 "title": "Golden Signals",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "p99 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (rate(http_request_duration_seconds_bucket[$__rate_interval]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(rate(http_requests_total{code=~\"5..\"}[$__rate_interval])) \n/\nclamp_min(sum(rate(http_requests_total[$__rate_interval])), 1e-9)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error % over time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\nsum(rate(http_requests_total{code=~\"5..\"}[1m])) \n/\nclamp_min(sum(rate(http_requests_total[1m])), 1e-9)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}